# vagrant init bento/debian-12.1 --box-version 202309.08.0

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12.1"
    config.vm.box_version = "202309.08.0"
  end

# vagrant destroy -f 
# vagrant up